// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlockltbwthtkslluzhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsb2NrbHRid3RodGtzbGx1emhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODcyODgsImV4cCI6MjA2NTY2MzI4OH0.598qkGLuo8BdMIB77y5cZgnkU2-WLjnENv7p6b_BK68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);